import { Wrapper } from "@/components/Common/Wrapper";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Wrapper>
          <main className="">{children}</main>
        </Wrapper>
        {/* <footer className="fixed bottom-0 left-0 right-0 text-center text-sm text-gray-500">
          <span className="font-bold mr-1">2025 Made by</span>
          <span className="font-bold text-violet-400 hover:text-violet-500 mr-1">
            <a href="https://iameddie.work" target="_blank">
              @Eddie
            </a>
          </span>
          <span className="font-bold mr-1">with curiosity</span>
        </footer> */}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
